# Generated by Django 4.0.4 on 2022-04-21 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="IS MY PORPOISE TO BE TESTES?",
                        max_length=64,
                        verbose_name="name",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="power",
                    ),
                ),
                ("consumers", models.CharField(default="", max_length=1024)),
            ],
        ),
    ]
