# Generated by Django 4.0.4 on 2022-05-24 04:02

import Solver.models
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('Solver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('ZS', 'Winter'), ('LS', 'Summer')], max_length=20)),
                ('academic_year_start', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=Solver.models.current_year, verbose_name='year')),
                ('academic_year_end', models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022)], default=functools.partial(Solver.models.current_year, *(1,), **{}), verbose_name='year')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='IS MY PORPOISE TO BE TESTED?', max_length=64, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('demands', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solver.demands', verbose_name='DemandsForTerm')),
                ('valuation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solver.items', verbose_name='ValuationForTerm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='demands',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Solver.term', verbose_name='Term'),
        ),
    ]
