# Generated by Django 4.0.4 on 2022-05-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solver', '0003_fieldofstudy_results_student_delete_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demands',
            options={'verbose_name': 'Demands', 'verbose_name_plural': 'Demands'},
        ),
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'verbose_name': 'Field of Study', 'verbose_name_plural': 'Fields of studies'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Items', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Results', 'verbose_name_plural': 'Results'},
        ),
        migrations.RemoveField(
            model_name='term',
            name='academic_year_end',
        ),
    ]
