# Generated by Django 4.0.4 on 2022-05-25 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solver', '0005_remove_student_results_remove_student_valuation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solver.fieldofstudy', verbose_name='Field of study'),
        ),
    ]
